import type { Movie } from '../../../shared/types/domain'
import { localDateKey } from '../../../shared/lib/format'

const TMDB_POSTER = (path: string) => `https://image.tmdb.org/t/p/w500${path}`
const TMDB_BACKDROP = (path: string) => `https://image.tmdb.org/t/p/w1280${path}`

function daysFromNow(days: number): string {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return localDateKey(date)
}

export const MOVIES: Movie[] = [
  {
    id: 'oppenheimer',
    title: 'Oppenheimer',
    synopsis:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb, and the moral reckoning that followed.",
    genres: ['Biography', 'Drama', 'History'],
    languages: ['English'],
    durationMinutes: 180,
    certification: 'UA',
    rating: 8.8,
    releaseDate: daysFromNow(-14),
    status: 'now-showing',
    posterUrl: TMDB_POSTER('/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg'),
    backdropUrl: TMDB_BACKDROP('/neeNHeXjMF5fXoCJRsOmkNGC7q.jpg'),
    director: 'Christopher Nolan',
    cast: [
      { name: 'Cillian Murphy', role: 'J. Robert Oppenheimer' },
      { name: 'Emily Blunt', role: 'Kitty Oppenheimer' },
      { name: 'Matt Damon', role: 'Leslie Groves' },
    ],
  },
  {
    id: 'dune',
    title: 'Dune',
    synopsis:
      'Paul Atreides leads nomadic tribes in a revolt against the galactic empire that destroyed his family, on a desert planet that holds the key to the universe.',
    genres: ['Sci-Fi', 'Adventure'],
    languages: ['English'],
    durationMinutes: 155,
    certification: 'UA',
    rating: 8.5,
    releaseDate: daysFromNow(-30),
    status: 'now-showing',
    posterUrl: TMDB_POSTER('/gDzOcq0pfeCeqMBwKIJlSmQpjkZ.jpg'),
    backdropUrl: TMDB_BACKDROP('/qVgZu5BTx6pu4owCvVOm4zjTfOi.jpg'),
    director: 'Denis Villeneuve',
    cast: [
      { name: 'Timothée Chalamet', role: 'Paul Atreides' },
      { name: 'Zendaya', role: 'Chani' },
      { name: 'Rebecca Ferguson', role: 'Lady Jessica' },
    ],
  },
  {
    id: 'spider-verse',
    title: 'Spider-Man: Into the Spider-Verse',
    synopsis:
      'Teen Miles Morales becomes Spider-Man and joins other spider-powered heroes from parallel dimensions to stop a threat to all of reality.',
    genres: ['Animation', 'Action', 'Adventure'],
    languages: ['English', 'Hindi'],
    durationMinutes: 117,
    certification: 'U',
    rating: 8.4,
    releaseDate: daysFromNow(-7),
    status: 'now-showing',
    posterUrl: TMDB_POSTER('/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg'),
    backdropUrl: TMDB_BACKDROP('/8mnXR9rey5uQ08rZAvzojKWbDQS.jpg'),
    director: 'Bob Persichetti',
    cast: [
      { name: 'Shameik Moore', role: 'Miles Morales (voice)' },
      { name: 'Hailee Steinfeld', role: 'Gwen Stacy (voice)' },
    ],
  },
  {
    id: 'barbie',
    title: 'Barbie',
    synopsis:
      'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land — until a trip to the real world begins.',
    genres: ['Comedy', 'Fantasy', 'Adventure'],
    languages: ['English'],
    durationMinutes: 114,
    certification: 'U',
    rating: 7.3,
    releaseDate: daysFromNow(-3),
    status: 'now-showing',
    posterUrl: TMDB_POSTER('/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg'),
    backdropUrl: TMDB_BACKDROP('/3N5QNUqS76GFYNoEayfkkJyAyTN.jpg'),
    director: 'Greta Gerwig',
    cast: [
      { name: 'Margot Robbie', role: 'Barbie' },
      { name: 'Ryan Gosling', role: 'Ken' },
      { name: 'America Ferrera', role: 'Gloria' },
    ],
  },
  {
    id: 'rrr',
    title: 'RRR',
    synopsis:
      'A fictional story of two legendary revolutionaries and their journey away from home, before they started fighting for their country in the 1920s.',
    genres: ['Action', 'Drama'],
    languages: ['Telugu', 'Hindi'],
    durationMinutes: 187,
    certification: 'UA',
    rating: 8.8,
    releaseDate: daysFromNow(-21),
    status: 'now-showing',
    posterUrl: TMDB_POSTER('/u0XUBNQWlOvrh0Gd97ARGpIkL0.jpg'),
    backdropUrl: TMDB_BACKDROP('/i0Y0wP8H6SRgjr6QmuwbtQbS24D.jpg'),
    director: 'S. S. Rajamouli',
    cast: [
      { name: 'N. T. Rama Rao Jr.', role: 'Komaram Bheem' },
      { name: 'Ram Charan', role: 'Alluri Sitarama Raju' },
    ],
  },
  {
    id: 'mad-max-fury-road',
    title: 'Mad Max: Fury Road',
    synopsis:
      'In a post-apocalyptic wasteland, Max teams up with Furiosa to flee a tyrannical warlord and his army in an armored truck.',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    languages: ['English'],
    durationMinutes: 120,
    certification: 'A',
    rating: 8.1,
    releaseDate: daysFromNow(-45),
    status: 'now-showing',
    posterUrl: TMDB_POSTER('/ulcAi4dKpAjHwYGS08vNyx9H6I9.jpg'),
    backdropUrl: TMDB_BACKDROP('/uT895WNwm0aIJRtGizcQhrejWUo.jpg'),
    director: 'George Miller',
    cast: [
      { name: 'Tom Hardy', role: 'Max Rockatansky' },
      { name: 'Charlize Theron', role: 'Furiosa' },
    ],
  },
  {
    id: 'the-matrix',
    title: 'The Matrix',
    synopsis:
      'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    genres: ['Sci-Fi', 'Action'],
    languages: ['English'],
    durationMinutes: 136,
    certification: 'UA',
    rating: 8.7,
    releaseDate: daysFromNow(-60),
    status: 'now-showing',
    posterUrl: TMDB_POSTER('/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg'),
    backdropUrl: TMDB_BACKDROP('/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg'),
    director: 'Lana Wachowski, Lilly Wachowski',
    cast: [
      { name: 'Keanu Reeves', role: 'Neo' },
      { name: 'Laurence Fishburne', role: 'Morpheus' },
      { name: 'Carrie-Anne Moss', role: 'Trinity' },
    ],
  },
  {
    id: 'avengers-endgame',
    title: 'Avengers: Endgame',
    synopsis:
      'The remaining Avengers assemble once more to reverse the damage caused by Thanos and restore balance to the universe.',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    languages: ['English', 'Hindi'],
    durationMinutes: 181,
    certification: 'UA',
    rating: 8.4,
    releaseDate: daysFromNow(-10),
    status: 'now-showing',
    posterUrl: TMDB_POSTER('/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg'),
    backdropUrl: TMDB_BACKDROP('/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg'),
    director: 'Anthony Russo, Joe Russo',
    cast: [
      { name: 'Robert Downey Jr.', role: 'Tony Stark' },
      { name: 'Chris Evans', role: 'Steve Rogers' },
      { name: 'Scarlett Johansson', role: 'Natasha Romanoff' },
    ],
  },
  {
    id: 'everything-everywhere',
    title: 'Everything Everywhere All at Once',
    synopsis:
      'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save existence by exploring other universes and connecting with the lives she could have led.',
    genres: ['Sci-Fi', 'Comedy', 'Action'],
    languages: ['English', 'Mandarin'],
    durationMinutes: 139,
    certification: 'UA',
    rating: 8.0,
    releaseDate: daysFromNow(-5),
    status: 'now-showing',
    posterUrl: TMDB_POSTER('/u68AjlvlutfEIcpmbYpKcdi09ut.jpg'),
    backdropUrl: TMDB_BACKDROP('/ss0Os3uWJfQAENILHZUdX8Tt1OC.jpg'),
    director: 'Daniel Kwan, Daniel Scheinert',
    cast: [
      { name: 'Michelle Yeoh', role: 'Evelyn Wang' },
      { name: 'Ke Huy Quan', role: 'Waymond Wang' },
    ],
  },
  {
    id: '3-idiots',
    title: '3 Idiots',
    synopsis:
      'Two friends search for their long-lost companion, reminiscing about the time they spent together at college and how he inspired them to think differently.',
    genres: ['Comedy', 'Drama'],
    languages: ['Hindi'],
    durationMinutes: 170,
    certification: 'U',
    rating: 8.4,
    releaseDate: daysFromNow(-25),
    status: 'now-showing',
    posterUrl: TMDB_POSTER('/66A9MqXOyVFCssoloscw79z8Tew.jpg'),
    backdropUrl: TMDB_BACKDROP('/8gT3UKtglLVpu0YfccwbmXZ5Eis.jpg'),
    director: 'Rajkumar Hirani',
    cast: [
      { name: 'Aamir Khan', role: 'Rancho' },
      { name: 'R. Madhavan', role: 'Farhan' },
      { name: 'Sharman Joshi', role: 'Raju' },
    ],
  },
  {
    id: 'inception',
    title: 'Inception',
    synopsis:
      'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    languages: ['English'],
    durationMinutes: 148,
    certification: 'UA',
    rating: 8.8,
    releaseDate: daysFromNow(9),
    status: 'upcoming',
    posterUrl: TMDB_POSTER('/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg'),
    backdropUrl: TMDB_BACKDROP('/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg'),
    director: 'Christopher Nolan',
    cast: [
      { name: 'Leonardo DiCaprio', role: 'Dom Cobb' },
      { name: 'Elliot Page', role: 'Ariadne' },
      { name: 'Tom Hardy', role: 'Eames' },
    ],
  },
  {
    id: 'the-dark-knight',
    title: 'The Dark Knight',
    synopsis:
      'Batman raises the stakes in his war on crime, taking on the Joker, a criminal mastermind who plunges Gotham into anarchy.',
    genres: ['Action', 'Crime', 'Drama'],
    languages: ['English'],
    durationMinutes: 152,
    certification: 'UA',
    rating: 9.0,
    releaseDate: daysFromNow(16),
    status: 'upcoming',
    posterUrl: TMDB_POSTER('/qJ2tW6WMUDux911r6m7haRef0WH.jpg'),
    backdropUrl: TMDB_BACKDROP('/dqK9Hag1054tghRQSqLSfrkvQnA.jpg'),
    director: 'Christopher Nolan',
    cast: [
      { name: 'Christian Bale', role: 'Bruce Wayne' },
      { name: 'Heath Ledger', role: 'The Joker' },
    ],
  },
  {
    id: 'interstellar',
    title: 'Interstellar',
    synopsis:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    genres: ['Sci-Fi', 'Drama', 'Adventure'],
    languages: ['English'],
    durationMinutes: 169,
    certification: 'UA',
    rating: 8.7,
    releaseDate: daysFromNow(23),
    status: 'upcoming',
    posterUrl: TMDB_POSTER('/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg'),
    backdropUrl: TMDB_BACKDROP('/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg'),
    director: 'Christopher Nolan',
    cast: [
      { name: 'Matthew McConaughey', role: 'Cooper' },
      { name: 'Anne Hathaway', role: 'Brand' },
    ],
  },
  {
    id: 'parasite',
    title: 'Parasite',
    synopsis:
      'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    genres: ['Thriller', 'Drama', 'Comedy'],
    languages: ['Korean'],
    durationMinutes: 132,
    certification: 'A',
    rating: 8.5,
    releaseDate: daysFromNow(12),
    status: 'upcoming',
    posterUrl: TMDB_POSTER('/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg'),
    backdropUrl: TMDB_BACKDROP('/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg'),
    director: 'Bong Joon-ho',
    cast: [
      { name: 'Song Kang-ho', role: 'Kim Ki-taek' },
      { name: 'Lee Sun-kyun', role: 'Park Dong-ik' },
    ],
  },
  {
    id: 'grand-budapest-hotel',
    title: 'The Grand Budapest Hotel',
    synopsis:
      'The adventures of a legendary concierge at a famous European hotel between the two World Wars, and the lobby boy who becomes his most trusted friend.',
    genres: ['Comedy', 'Drama'],
    languages: ['English'],
    durationMinutes: 99,
    certification: 'UA',
    rating: 8.1,
    releaseDate: daysFromNow(19),
    status: 'upcoming',
    posterUrl: TMDB_POSTER('/zOVCqKUzjFKqa1eDMcOzvXwthY4.jpg'),
    backdropUrl: TMDB_BACKDROP('/9udCLTxTFl28RxnK8Q05E154ZGa.jpg'),
    director: 'Wes Anderson',
    cast: [
      { name: 'Ralph Fiennes', role: 'Gustave H.' },
      { name: 'Tony Revolori', role: 'Zero Moustafa' },
    ],
  },
  {
    id: 'whiplash',
    title: 'Whiplash',
    synopsis:
      'A promising young drummer enrolls at a cutthroat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.',
    genres: ['Drama', 'Music'],
    languages: ['English'],
    durationMinutes: 106,
    certification: 'A',
    rating: 8.5,
    releaseDate: daysFromNow(5),
    status: 'upcoming',
    posterUrl: TMDB_POSTER('/7fn624j5lj3xTme2SgiLCeuedmO.jpg'),
    backdropUrl: TMDB_BACKDROP('/wbQa0EnWUyRzQ5d1pHLNRlmsCUP.jpg'),
    director: 'Damien Chazelle',
    cast: [
      { name: 'Miles Teller', role: 'Andrew Neiman' },
      { name: 'J. K. Simmons', role: 'Terence Fletcher' },
    ],
  },
  {
    id: 'la-la-land',
    title: 'La La Land',
    synopsis:
      'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
    genres: ['Musical', 'Romance', 'Drama'],
    languages: ['English'],
    durationMinutes: 128,
    certification: 'U',
    rating: 8.0,
    releaseDate: daysFromNow(27),
    status: 'upcoming',
    posterUrl: TMDB_POSTER('/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg'),
    backdropUrl: TMDB_BACKDROP('/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg'),
    director: 'Damien Chazelle',
    cast: [
      { name: 'Ryan Gosling', role: 'Sebastian' },
      { name: 'Emma Stone', role: 'Mia' },
    ],
  },
  {
    id: 'pulp-fiction',
    title: 'Pulp Fiction',
    synopsis:
      'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
    genres: ['Crime', 'Drama'],
    languages: ['English'],
    durationMinutes: 154,
    certification: 'A',
    rating: 8.9,
    releaseDate: daysFromNow(33),
    status: 'upcoming',
    posterUrl: TMDB_POSTER('/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg'),
    backdropUrl: TMDB_BACKDROP('/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg'),
    director: 'Quentin Tarantino',
    cast: [
      { name: 'John Travolta', role: 'Vincent Vega' },
      { name: 'Samuel L. Jackson', role: 'Jules Winnfield' },
    ],
  },
]

export const ALL_GENRES = Array.from(new Set(MOVIES.flatMap((movie) => movie.genres))).sort()
export const ALL_LANGUAGES = Array.from(new Set(MOVIES.flatMap((movie) => movie.languages))).sort()
