const STATUS_BY_CODE: Record<string, number> = {
  NO_SEATS_SELECTED: 400,
  SEATS_UNAVAILABLE: 409,
  HOLD_EXPIRED: 410,
  MOVIE_NOT_FOUND: 404,
  CINEMA_NOT_FOUND: 404,
  SCREEN_NOT_FOUND: 404,
  SHOW_NOT_FOUND: 404,
  HOLD_NOT_FOUND: 404,
  BOOKING_NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  UNAUTHENTICATED: 401,
  INVALID_CREDENTIALS: 401,
  FORBIDDEN: 403,
  EMAIL_TAKEN: 409,
  VALIDATION_ERROR: 400,
}

export function statusForErrorCode(code: string): number {
  return STATUS_BY_CODE[code] ?? 400
}
